import * as THREE from 'three';
export function createStadium(container,getState){
 let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch{container.innerHTML='<div class="webgl-fallback">3D viewing needs WebGL. Match commentary and controls are still available.</div>';return{dispose(){},toggleCamera(){},goal(){}};}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;container.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#a6bac4');scene.fog=new THREE.Fog('#a6bac4',110,245);
 const camera=new THREE.PerspectiveCamera(44,1,.1,350);let alternate=false;camera.position.set(73,61,79);camera.lookAt(0,0,0);
 scene.add(new THREE.HemisphereLight(0xe8f6ff,0x536735,2.3));const sun=new THREE.DirectionalLight(0xffedce,3.5);sun.position.set(-35,70,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-85,right:85,top:85,bottom:-85,near:1,far:200});sun.shadow.bias=-.0004;scene.add(sun);
 const mat=(color,roughness=.8)=>new THREE.MeshStandardMaterial({color,roughness});const green=mat('#386844'),dark=mat('#263b35'),concrete=mat('#8c9290'),white=mat('#f1f0da'),blue=mat('#273d50');
 function box(w,h,d,x,y,z,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o;}
 box(140,1,105,0,-1,0,dark);for(let i=0;i<14;i++)box(7.5,.16,68,-48.75+i*7.5,0,0,mat(i%2?'#508650':'#477b48'));
 const lineMaterial=new THREE.LineBasicMaterial({color:0xf4f0de});function line(points){const g=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(p[0],.12,p[1])));scene.add(new THREE.Line(g,lineMaterial));}function rect(x1,z1,x2,z2){line([[x1,z1],[x2,z1],[x2,z2],[x1,z2],[x1,z1]])}rect(-52.5,-34,52.5,34);line([[0,-34],[0,34]]);for(const side of [-1,1]){rect(side*52.5,-20.15,side*36,20.15);rect(side*52.5,-9.15,side*47,9.15);const dot=new THREE.Mesh(new THREE.CircleGeometry(.22,12),white);dot.rotation.x=-Math.PI/2;dot.position.set(side*41.5,.13,0);scene.add(dot);}
 const circle=[];for(let i=0;i<=80;i++){const a=i/80*Math.PI*2;circle.push([Math.cos(a)*9.15,Math.sin(a)*9.15])}line(circle);
 for(const side of [-1,1]){const x=side*53;box(.2,2.44,.2,x,1.22,-3.66,white);box(.2,2.44,.2,x,1.22,3.66,white);box(.2,.2,7.5,x,2.44,0,white);const net=new THREE.MeshBasicMaterial({color:'#e5e9df',transparent:true,opacity:.2,wireframe:true});box(2.6,2.44,7.32,x+side*1.3,1.22,0,net);for(let z=-3.6;z<3.7;z+=.45){const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(x,.15,z),new THREE.Vector3(x+side*2.6,.15,z),new THREE.Vector3(x+side*2.6,2.44,z),new THREE.Vector3(x,2.44,z)]);scene.add(new THREE.Line(geo,new THREE.LineBasicMaterial({color:'#d4ded4',transparent:true,opacity:.45})));}}
 // Tiered stands, colorful seats and spectator silhouettes.
 for(const side of [-1,1]){for(let row=0;row<9;row++){box(126,1.1,2.3,0,1+row*1.2,side*(40+row*2),concrete);box(126,.2,1.6,0,1.65+row*1.2,side*(40+row*2),row%3===0?white:blue);}box(130,1.2,23,0,15,side*49,mat('#293c40'));box(130,.3,24,0,15.8,side*49,mat('#60716e'));for(let x=-60;x<=60;x+=20)box(.7,15,.7,x,7.5,side*59,dark);}
 for(const side of [-1,1])for(let row=0;row<7;row++){box(2.3,1.2,77,side*(60+row*2),1+row*1.2,0,concrete);box(1.6,.2,77,side*(60+row*2),1.7+row*1.2,0,blue);}
 const crowdGeo=new THREE.SphereGeometry(.32,5,4);const crowd=new THREE.InstancedMesh(crowdGeo,mat('#bcb8a6'),1600);const dummy=new THREE.Object3D();let ci=0;for(let side of [-1,1])for(let row=0;row<8;row++)for(let j=0;j<100;j++){dummy.position.set(-60+j*1.2,2.3+row*1.2,side*(40+row*2));dummy.scale.set(1,1.8,1);dummy.updateMatrix();crowd.setMatrixAt(ci,dummy.matrix);crowd.setColorAt(ci,new THREE.Color(['#e7e0c9','#1e353a','#617a79','#b3a272','#a8bc64'][j%5]));ci++;}scene.add(crowd);
 const adCanvas=document.createElement('canvas');adCanvas.width=1024;adCanvas.height=64;const ctx=adCanvas.getContext('2d');ctx.fillStyle='#d4eb8d';ctx.fillRect(0,0,1024,64);ctx.fillStyle='#243229';ctx.font='bold 27px sans-serif';ctx.fillText('TOUCHLINE     •     THE BEAUTIFUL GAME. YOUR WAY.     •     TOUCHLINE',20,42);const texture=new THREE.CanvasTexture(adCanvas);for(const side of [-1,1]){const ad=new THREE.Mesh(new THREE.PlaneGeometry(110,1.8),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide}));ad.position.set(0,1,side*37);scene.add(ad);}
 for(const x of [-64,64])for(const z of [-42,42]){box(.35,23,.35,x,11.5,z,concrete);box(4.5,2,.6,x,23,z,white);}
 const figures=[];const skin=mat('#c48b68');function player(team,i){const g=new THREE.Group();const shirt=mat(team===0?'#e7f0db':'#192e54');const body=new THREE.Mesh(new THREE.CapsuleGeometry(.32,.55,3,6),shirt);body.position.y=1.15;body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.23,8,7),skin);head.position.y=1.9;head.castShadow=true;g.add(head);const shorts=new THREE.Mesh(new THREE.BoxGeometry(.58,.4,.36),team===0?dark:blue);shorts.position.y=.72;g.add(shorts);const legs=[];for(const s of [-1,1]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.09,.5,2,5),shirt);leg.position.set(s*.17,.35,0);leg.castShadow=true;g.add(leg);legs.push(leg);}const pos=[[-43,0],[-29,-22],[-33,-8],[-33,9],[-28,24],[-13,-18],[-17,0],[-10,18],[10,-23],[18,0],[10,23]][i];g.position.set(team===0?pos[0]:-pos[0],.2,team===0?pos[1]:-pos[1]);scene.add(g);figures.push({g,base:g.position.clone(),legs,i,team});}for(let t=0;t<2;t++)for(let i=0;i<11;i++)player(t,i);
 const ball=new THREE.Mesh(new THREE.IcosahedronGeometry(.38,1),mat('#faf8ee'));ball.castShadow=true;scene.add(ball);const ballMarks=new THREE.Mesh(new THREE.IcosahedronGeometry(.385,0),new THREE.MeshBasicMaterial({color:'#1c2925',wireframe:true}));ball.add(ballMarks);let raf,goalUntil=0,goalStart=0,goalSide=1;const clock=new THREE.Clock();function resize(){const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}const observer=new ResizeObserver(resize);observer.observe(container);resize();
 function animate(){raf=requestAnimationFrame(animate);const t=clock.getElapsedTime(),s=getState();const movement=s.playing?t:0;for(const p of figures){p.g.position.x=p.base.x+Math.sin(movement*.5+p.i)* (s.playing?8:1);p.g.position.z=p.base.z+Math.cos(movement*.6+p.i)* (s.playing?5:.4);p.legs.forEach((l,i)=>l.rotation.x=s.playing?Math.sin(t*8+i*Math.PI+p.i)*.6:0);p.g.rotation.y=p.team===0?Math.PI/2:-Math.PI/2;}const goal=t<goalUntil;const shot=Math.min(1,(t-goalStart)/2);ball.position.set(goal?goalSide*(24+30*shot):(s.playing?Math.sin(t*.4)*35:0),goal?.42+Math.sin(shot*Math.PI)*1.8:.42+(s.playing?Math.abs(Math.sin(t*2))*.3:0),goal?4*(1-shot):(s.playing?Math.cos(t*.7)*17:0));ball.rotation.z=t;const target=goal?new THREE.Vector3(goalSide*30,20,35):alternate?new THREE.Vector3(0,70,50):new THREE.Vector3(73,61,79);camera.position.lerp(target,.04);camera.lookAt(goal?goalSide*40:0,0,0);renderer.render(scene,camera);}animate();return{toggleCamera(){alternate=!alternate},goal(side=1){goalSide=side;goalStart=clock.getElapsedTime();goalUntil=goalStart+4},dispose(){cancelAnimationFrame(raf);observer.disconnect();scene.traverse(o=>{o.geometry?.dispose();if(o.material){const a=Array.isArray(o.material)?o.material:[o.material];a.forEach(m=>{m.map?.dispose();m.dispose()})}});renderer.dispose();renderer.domElement.remove()}};
}
